variable "domain-name" {}
variable "jenkins_domain_name" {}
variable "jenkins_lb_dns_name" {}
variable "jenkins_lb_zone_id" {}
variable "nexus_domain_name" {}
variable "nexus_lb_dns_name" {}
variable "nexus_lb_zone_id" {}
variable "sonarqube_domain_name" {}
variable "sonarqube_lb_dns_name" {}
variable "sonarqube_lb_zone_id" {}
variable "prod_domain_name" {}
variable "prod_lb_dns_name" {}
variable "prod_lb_zone_id" {}
variable "stage_domain_name" {}
variable "stage_lb_dns_name" {}
variable "stage_lb_zone_id" {}
variable "prom_domain_name" {}
variable "prom_lb_dns_name" {}
variable "prom_lb_zone_id" {}
variable "graf_domain_name" {}
variable "graf_lb_dns_name" {}
variable "graf_lb_zone_id" {}